schema: ./source/server/graphql/schema.graphql
documents: ./source/client/**/*.graphql
generates:
  ./source/client/common/graphql/types/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node